//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.17 at 03:52:09 PM IST 
//


package org.iata.iata.edist;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iata.iata.edist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AirportCode_QNAME = new QName("http://www.iata.org/IATA/EDIST", "AirportCode");
    private final static QName _Code_QNAME = new QName("http://www.iata.org/IATA/EDIST", "Code");
    private final static QName _Arrival_QNAME = new QName("http://www.iata.org/IATA/EDIST", "Arrival");
    private final static QName _Date_QNAME = new QName("http://www.iata.org/IATA/EDIST", "Date");
    private final static QName _CurrCode_QNAME = new QName("http://www.iata.org/IATA/EDIST", "CurrCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iata.iata.edist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CityCode }
     * 
     */
    public CityCode createCityCode() {
        return new CityCode();
    }

    /**
     * Create an instance of {@link Types }
     * 
     */
    public Types createTypes() {
        return new Types();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link AirportMetadatas }
     * 
     */
    public AirportMetadatas createAirportMetadatas() {
        return new AirportMetadatas();
    }

    /**
     * Create an instance of {@link AirportMetadata }
     * 
     */
    public AirportMetadata createAirportMetadata() {
        return new AirportMetadata();
    }

    /**
     * Create an instance of {@link AugmentationPoint }
     * 
     */
    public AugmentationPoint createAugmentationPoint() {
        return new AugmentationPoint();
    }

    /**
     * Create an instance of {@link AugPoint }
     * 
     */
    public AugPoint createAugPoint() {
        return new AugPoint();
    }

    /**
     * Create an instance of {@link Lists }
     * 
     */
    public Lists createLists() {
        return new Lists();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link AugPointAssoc }
     * 
     */
    public AugPointAssoc createAugPointAssoc() {
        return new AugPointAssoc();
    }

    /**
     * Create an instance of {@link NamedAssocs }
     * 
     */
    public NamedAssocs createNamedAssocs() {
        return new NamedAssocs();
    }

    /**
     * Create an instance of {@link NamedAssoc }
     * 
     */
    public NamedAssoc createNamedAssoc() {
        return new NamedAssoc();
    }

    /**
     * Create an instance of {@link PointOfSale }
     * 
     */
    public PointOfSale createPointOfSale() {
        return new PointOfSale();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link CountryCode }
     * 
     */
    public CountryCode createCountryCode() {
        return new CountryCode();
    }

    /**
     * Create an instance of {@link Flight }
     * 
     */
    public Flight createFlight() {
        return new Flight();
    }

    /**
     * Create an instance of {@link FlightMetadatas }
     * 
     */
    public FlightMetadatas createFlightMetadatas() {
        return new FlightMetadatas();
    }

    /**
     * Create an instance of {@link FlightMetadata }
     * 
     */
    public FlightMetadata createFlightMetadata() {
        return new FlightMetadata();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Shopping }
     * 
     */
    public Shopping createShopping() {
        return new Shopping();
    }

    /**
     * Create an instance of {@link ShopMetadataGroup }
     * 
     */
    public ShopMetadataGroup createShopMetadataGroup() {
        return new ShopMetadataGroup();
    }

    /**
     * Create an instance of {@link Other }
     * 
     */
    public Other createOther() {
        return new Other();
    }

    /**
     * Create an instance of {@link OtherMetadata }
     * 
     */
    public OtherMetadata createOtherMetadata() {
        return new OtherMetadata();
    }

    /**
     * Create an instance of {@link AnonymousTraveler }
     * 
     */
    public AnonymousTraveler createAnonymousTraveler() {
        return new AnonymousTraveler();
    }

    /**
     * Create an instance of {@link PTC }
     * 
     */
    public PTC createPTC() {
        return new PTC();
    }

    /**
     * Create an instance of {@link Departure }
     * 
     */
    public Departure createDeparture() {
        return new Departure();
    }

    /**
     * Create an instance of {@link AirportCode }
     * 
     */
    public AirportCode createAirportCode() {
        return new AirportCode();
    }

    /**
     * Create an instance of {@link OriginDestinations }
     * 
     */
    public OriginDestinations createOriginDestinations() {
        return new OriginDestinations();
    }

    /**
     * Create an instance of {@link OriginDestination }
     * 
     */
    public OriginDestination createOriginDestination() {
        return new OriginDestination();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public Preferences createPreferences() {
        return new Preferences();
    }

    /**
     * Create an instance of {@link Preference }
     * 
     */
    public Preference createPreference() {
        return new Preference();
    }

    /**
     * Create an instance of {@link CabinPreferences }
     * 
     */
    public CabinPreferences createCabinPreferences() {
        return new CabinPreferences();
    }

    /**
     * Create an instance of {@link CabinType }
     * 
     */
    public CabinType createCabinType() {
        return new CabinType();
    }

    /**
     * Create an instance of {@link FarePreferences }
     * 
     */
    public FarePreferences createFarePreferences() {
        return new FarePreferences();
    }

    /**
     * Create an instance of {@link CoreQuery }
     * 
     */
    public CoreQuery createCoreQuery() {
        return new CoreQuery();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link CurrCodes }
     * 
     */
    public CurrCodes createCurrCodes() {
        return new CurrCodes();
    }

    /**
     * Create an instance of {@link Travelers }
     * 
     */
    public Travelers createTravelers() {
        return new Travelers();
    }

    /**
     * Create an instance of {@link Traveler }
     * 
     */
    public Traveler createTraveler() {
        return new Traveler();
    }

    /**
     * Create an instance of {@link AirShoppingRQ }
     * 
     */
    public AirShoppingRQ createAirShoppingRQ() {
        return new AirShoppingRQ();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iata.org/IATA/EDIST", name = "AirportCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAirportCode(String value) {
        return new JAXBElement<String>(_AirportCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iata.org/IATA/EDIST", name = "Code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AirportCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iata.org/IATA/EDIST", name = "Arrival")
    public JAXBElement<AirportCode> createArrival(AirportCode value) {
        return new JAXBElement<AirportCode>(_Arrival_QNAME, AirportCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iata.org/IATA/EDIST", name = "Date")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iata.org/IATA/EDIST", name = "CurrCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCurrCode(String value) {
        return new JAXBElement<String>(_CurrCode_QNAME, String.class, null, value);
    }

}
