//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 04:20:21 PM IST 
//


package org.xmlsoap.schemas.soap.envelope;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.iata.iata.edist.AirShoppingRQ;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.iata.org/IATA/EDIST}AirShoppingRQ"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "airShoppingRQ"
})
@XmlRootElement(name = "Body")
public class Body {

    @XmlElement(name = "AirShoppingRQ", namespace = "http://www.iata.org/IATA/EDIST", required = true)
    protected AirShoppingRQ airShoppingRQ;

    /**
     * Gets the value of the airShoppingRQ property.
     * 
     * @return
     *     possible object is
     *     {@link AirShoppingRQ }
     *     
     */
    public AirShoppingRQ getAirShoppingRQ() {
        return airShoppingRQ;
    }

    /**
     * Sets the value of the airShoppingRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirShoppingRQ }
     *     
     */
    public void setAirShoppingRQ(AirShoppingRQ value) {
        this.airShoppingRQ = value;
    }

}
